// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/control.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HospitalParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of simultaneous infections that can be treated.
	Capacity int32 `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// Scale factor applied to death probability when capacity is exceeded.
	DeathRateOverloadMultiplier float64 `protobuf:"fixed64,2,opt,name=death_rate_overload_multiplier,json=deathRateOverloadMultiplier,proto3" json:"death_rate_overload_multiplier,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *HospitalParameters) Reset() {
	*x = HospitalParameters{}
	mi := &file_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HospitalParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HospitalParameters) ProtoMessage() {}

func (x *HospitalParameters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HospitalParameters.ProtoReflect.Descriptor instead.
func (*HospitalParameters) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{0}
}

func (x *HospitalParameters) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *HospitalParameters) GetDeathRateOverloadMultiplier() float64 {
	if x != nil {
		return x.DeathRateOverloadMultiplier
	}
	return 0
}

type ControlUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// transmission_rate scales the base infection probability (0.0 - 1.0).
	TransmissionRate float64 `protobuf:"fixed64,1,opt,name=transmission_rate,json=transmissionRate,proto3" json:"transmission_rate,omitempty"`
	// lockdown_enabled toggles reduced movement speed for agents.
	LockdownEnabled bool `protobuf:"varint,2,opt,name=lockdown_enabled,json=lockdownEnabled,proto3" json:"lockdown_enabled,omitempty"`
	// hospital encapsulates capacity and overload parameters.
	Hospital      *HospitalParameters `protobuf:"bytes,3,opt,name=hospital,proto3" json:"hospital,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlUpdate) Reset() {
	*x = ControlUpdate{}
	mi := &file_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlUpdate) ProtoMessage() {}

func (x *ControlUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlUpdate.ProtoReflect.Descriptor instead.
func (*ControlUpdate) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *ControlUpdate) GetTransmissionRate() float64 {
	if x != nil {
		return x.TransmissionRate
	}
	return 0
}

func (x *ControlUpdate) GetLockdownEnabled() bool {
	if x != nil {
		return x.LockdownEnabled
	}
	return false
}

func (x *ControlUpdate) GetHospital() *HospitalParameters {
	if x != nil {
		return x.Hospital
	}
	return nil
}

type ControlState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// settings reflects the current control values applied on the server.
	Settings *ControlUpdate `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	// current_infected reflects the latest infected count computed by the backend.
	CurrentInfected int32 `protobuf:"varint,2,opt,name=current_infected,json=currentInfected,proto3" json:"current_infected,omitempty"`
	// effective_death_probability is the per-tick death probability after overload effects.
	EffectiveDeathProbability float64 `protobuf:"fixed64,3,opt,name=effective_death_probability,json=effectiveDeathProbability,proto3" json:"effective_death_probability,omitempty"`
	// overloaded flags whether infections are currently above hospital capacity.
	Overloaded bool `protobuf:"varint,4,opt,name=overloaded,proto3" json:"overloaded,omitempty"`
	// infection_probability is the effective probability after applying the rate modifier.
	InfectionProbability float64 `protobuf:"fixed64,5,opt,name=infection_probability,json=infectionProbability,proto3" json:"infection_probability,omitempty"`
	// speed_modifier tracks the movement multiplier applied to agents (1.0 is normal speed).
	SpeedModifier float64 `protobuf:"fixed64,6,opt,name=speed_modifier,json=speedModifier,proto3" json:"speed_modifier,omitempty"`
	// capacity_utilization expresses how much of the configured capacity is currently used.
	CapacityUtilization float64 `protobuf:"fixed64,7,opt,name=capacity_utilization,json=capacityUtilization,proto3" json:"capacity_utilization,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ControlState) Reset() {
	*x = ControlState{}
	mi := &file_proto_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlState) ProtoMessage() {}

func (x *ControlState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlState.ProtoReflect.Descriptor instead.
func (*ControlState) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{2}
}

func (x *ControlState) GetSettings() *ControlUpdate {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ControlState) GetCurrentInfected() int32 {
	if x != nil {
		return x.CurrentInfected
	}
	return 0
}

func (x *ControlState) GetEffectiveDeathProbability() float64 {
	if x != nil {
		return x.EffectiveDeathProbability
	}
	return 0
}

func (x *ControlState) GetOverloaded() bool {
	if x != nil {
		return x.Overloaded
	}
	return false
}

func (x *ControlState) GetInfectionProbability() float64 {
	if x != nil {
		return x.InfectionProbability
	}
	return 0
}

func (x *ControlState) GetSpeedModifier() float64 {
	if x != nil {
		return x.SpeedModifier
	}
	return 0
}

func (x *ControlState) GetCapacityUtilization() float64 {
	if x != nil {
		return x.CapacityUtilization
	}
	return 0
}

type ControlAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional informational text returned after applying a client update.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// state contains the server's current control state for synchronization.
	State         *ControlState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlAck) Reset() {
	*x = ControlAck{}
	mi := &file_proto_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlAck) ProtoMessage() {}

func (x *ControlAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlAck.ProtoReflect.Descriptor instead.
func (*ControlAck) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{3}
}

func (x *ControlAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ControlAck) GetState() *ControlState {
	if x != nil {
		return x.State
	}
	return nil
}

type ControlError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-friendly description of why an update failed.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlError) Reset() {
	*x = ControlError{}
	mi := &file_proto_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlError) ProtoMessage() {}

func (x *ControlError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlError.ProtoReflect.Descriptor instead.
func (*ControlError) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{4}
}

func (x *ControlError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Control:
	//
	//	*ControlMessage_Update
	//	*ControlMessage_State
	//	*ControlMessage_Ack
	//	*ControlMessage_Error
	Control       isControlMessage_Control `protobuf_oneof:"control"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_proto_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{5}
}

func (x *ControlMessage) GetControl() isControlMessage_Control {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *ControlMessage) GetUpdate() *ControlUpdate {
	if x != nil {
		if x, ok := x.Control.(*ControlMessage_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *ControlMessage) GetState() *ControlState {
	if x != nil {
		if x, ok := x.Control.(*ControlMessage_State); ok {
			return x.State
		}
	}
	return nil
}

func (x *ControlMessage) GetAck() *ControlAck {
	if x != nil {
		if x, ok := x.Control.(*ControlMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ControlMessage) GetError() *ControlError {
	if x != nil {
		if x, ok := x.Control.(*ControlMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isControlMessage_Control interface {
	isControlMessage_Control()
}

type ControlMessage_Update struct {
	Update *ControlUpdate `protobuf:"bytes,1,opt,name=update,proto3,oneof"`
}

type ControlMessage_State struct {
	State *ControlState `protobuf:"bytes,2,opt,name=state,proto3,oneof"`
}

type ControlMessage_Ack struct {
	Ack *ControlAck `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type ControlMessage_Error struct {
	Error *ControlError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ControlMessage_Update) isControlMessage_Control() {}

func (*ControlMessage_State) isControlMessage_Control() {}

func (*ControlMessage_Ack) isControlMessage_Control() {}

func (*ControlMessage_Error) isControlMessage_Control() {}

var File_proto_control_proto protoreflect.FileDescriptor

const file_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x13proto/control.proto\x12\tpandemica\"u\n" +
	"\x12HospitalParameters\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x05R\bcapacity\x12C\n" +
	"\x1edeath_rate_overload_multiplier\x18\x02 \x01(\x01R\x1bdeathRateOverloadMultiplier\"\xa2\x01\n" +
	"\rControlUpdate\x12+\n" +
	"\x11transmission_rate\x18\x01 \x01(\x01R\x10transmissionRate\x12)\n" +
	"\x10lockdown_enabled\x18\x02 \x01(\bR\x0flockdownEnabled\x129\n" +
	"\bhospital\x18\x03 \x01(\v2\x1d.pandemica.HospitalParametersR\bhospital\"\xde\x02\n" +
	"\fControlState\x124\n" +
	"\bsettings\x18\x01 \x01(\v2\x18.pandemica.ControlUpdateR\bsettings\x12)\n" +
	"\x10current_infected\x18\x02 \x01(\x05R\x0fcurrentInfected\x12>\n" +
	"\x1beffective_death_probability\x18\x03 \x01(\x01R\x19effectiveDeathProbability\x12\x1e\n" +
	"\n" +
	"overloaded\x18\x04 \x01(\bR\n" +
	"overloaded\x123\n" +
	"\x15infection_probability\x18\x05 \x01(\x01R\x14infectionProbability\x12%\n" +
	"\x0espeed_modifier\x18\x06 \x01(\x01R\rspeedModifier\x121\n" +
	"\x14capacity_utilization\x18\a \x01(\x01R\x13capacityUtilization\"U\n" +
	"\n" +
	"ControlAck\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12-\n" +
	"\x05state\x18\x02 \x01(\v2\x17.pandemica.ControlStateR\x05state\"(\n" +
	"\fControlError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xdc\x01\n" +
	"\x0eControlMessage\x122\n" +
	"\x06update\x18\x01 \x01(\v2\x18.pandemica.ControlUpdateH\x00R\x06update\x12/\n" +
	"\x05state\x18\x02 \x01(\v2\x17.pandemica.ControlStateH\x00R\x05state\x12)\n" +
	"\x03ack\x18\x03 \x01(\v2\x15.pandemica.ControlAckH\x00R\x03ack\x12/\n" +
	"\x05error\x18\x04 \x01(\v2\x17.pandemica.ControlErrorH\x00R\x05errorB\t\n" +
	"\acontrolB\x11Z\x0fpandemica/protob\x06proto3"

var (
	file_proto_control_proto_rawDescOnce sync.Once
	file_proto_control_proto_rawDescData []byte
)

func file_proto_control_proto_rawDescGZIP() []byte {
	file_proto_control_proto_rawDescOnce.Do(func() {
		file_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)))
	})
	return file_proto_control_proto_rawDescData
}

var file_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_control_proto_goTypes = []any{
	(*HospitalParameters)(nil), // 0: pandemica.HospitalParameters
	(*ControlUpdate)(nil),      // 1: pandemica.ControlUpdate
	(*ControlState)(nil),       // 2: pandemica.ControlState
	(*ControlAck)(nil),         // 3: pandemica.ControlAck
	(*ControlError)(nil),       // 4: pandemica.ControlError
	(*ControlMessage)(nil),     // 5: pandemica.ControlMessage
}
var file_proto_control_proto_depIdxs = []int32{
	0, // 0: pandemica.ControlUpdate.hospital:type_name -> pandemica.HospitalParameters
	1, // 1: pandemica.ControlState.settings:type_name -> pandemica.ControlUpdate
	2, // 2: pandemica.ControlAck.state:type_name -> pandemica.ControlState
	1, // 3: pandemica.ControlMessage.update:type_name -> pandemica.ControlUpdate
	2, // 4: pandemica.ControlMessage.state:type_name -> pandemica.ControlState
	3, // 5: pandemica.ControlMessage.ack:type_name -> pandemica.ControlAck
	4, // 6: pandemica.ControlMessage.error:type_name -> pandemica.ControlError
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_control_proto_init() }
func file_proto_control_proto_init() {
	if File_proto_control_proto != nil {
		return
	}
	file_proto_control_proto_msgTypes[5].OneofWrappers = []any{
		(*ControlMessage_Update)(nil),
		(*ControlMessage_State)(nil),
		(*ControlMessage_Ack)(nil),
		(*ControlMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_control_proto_goTypes,
		DependencyIndexes: file_proto_control_proto_depIdxs,
		MessageInfos:      file_proto_control_proto_msgTypes,
	}.Build()
	File_proto_control_proto = out.File
	file_proto_control_proto_goTypes = nil
	file_proto_control_proto_depIdxs = nil
}
