// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: proto/control.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HospitalParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Maximum number of simultaneous infections that can be treated.
	Capacity int32 `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// Scale factor applied to death probability when capacity is exceeded.
	DeathRateOverloadMultiplier float64 `protobuf:"fixed64,2,opt,name=death_rate_overload_multiplier,json=deathRateOverloadMultiplier,proto3" json:"death_rate_overload_multiplier,omitempty"`
}

func (x *HospitalParameters) Reset() {
	*x = HospitalParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HospitalParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HospitalParameters) ProtoMessage() {}

func (x *HospitalParameters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HospitalParameters.ProtoReflect.Descriptor instead.
func (*HospitalParameters) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{0}
}

func (x *HospitalParameters) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *HospitalParameters) GetDeathRateOverloadMultiplier() float64 {
	if x != nil {
		return x.DeathRateOverloadMultiplier
	}
	return 0
}

type ControlUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// transmission_rate scales the base infection probability (0.0 - 1.0).
	TransmissionRate float64 `protobuf:"fixed64,1,opt,name=transmission_rate,json=transmissionRate,proto3" json:"transmission_rate,omitempty"`
	// lockdown_enabled toggles reduced movement speed for agents.
	LockdownEnabled bool `protobuf:"varint,2,opt,name=lockdown_enabled,json=lockdownEnabled,proto3" json:"lockdown_enabled,omitempty"`
	// hospital encapsulates capacity and overload parameters.
	Hospital *HospitalParameters `protobuf:"bytes,3,opt,name=hospital,proto3" json:"hospital,omitempty"`
}

func (x *ControlUpdate) Reset() {
	*x = ControlUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlUpdate) ProtoMessage() {}

func (x *ControlUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlUpdate.ProtoReflect.Descriptor instead.
func (*ControlUpdate) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *ControlUpdate) GetTransmissionRate() float64 {
	if x != nil {
		return x.TransmissionRate
	}
	return 0
}

func (x *ControlUpdate) GetLockdownEnabled() bool {
	if x != nil {
		return x.LockdownEnabled
	}
	return false
}

func (x *ControlUpdate) GetHospital() *HospitalParameters {
	if x != nil {
		return x.Hospital
	}
	return nil
}

type ControlState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// settings reflects the current control values applied on the server.
	Settings *ControlUpdate `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	// current_infected reflects the latest infected count computed by the backend.
	CurrentInfected int32 `protobuf:"varint,2,opt,name=current_infected,json=currentInfected,proto3" json:"current_infected,omitempty"`
	// effective_death_probability is the per-tick death probability after overload effects.
	EffectiveDeathProbability float64 `protobuf:"fixed64,3,opt,name=effective_death_probability,json=effectiveDeathProbability,proto3" json:"effective_death_probability,omitempty"`
	// overloaded flags whether infections are currently above hospital capacity.
	Overloaded bool `protobuf:"varint,4,opt,name=overloaded,proto3" json:"overloaded,omitempty"`
	// infection_probability is the effective probability after applying the rate modifier.
	InfectionProbability float64 `protobuf:"fixed64,5,opt,name=infection_probability,json=infectionProbability,proto3" json:"infection_probability,omitempty"`
}

func (x *ControlState) Reset() {
	*x = ControlState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlState) ProtoMessage() {}

func (x *ControlState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlState.ProtoReflect.Descriptor instead.
func (*ControlState) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{2}
}

func (x *ControlState) GetSettings() *ControlUpdate {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ControlState) GetCurrentInfected() int32 {
	if x != nil {
		return x.CurrentInfected
	}
	return 0
}

func (x *ControlState) GetEffectiveDeathProbability() float64 {
	if x != nil {
		return x.EffectiveDeathProbability
	}
	return 0
}

func (x *ControlState) GetOverloaded() bool {
	if x != nil {
		return x.Overloaded
	}
	return false
}

func (x *ControlState) GetInfectionProbability() float64 {
	if x != nil {
		return x.InfectionProbability
	}
	return 0
}

type ControlAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Optional informational text returned after applying a client update.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// state contains the server's current control state for synchronization.
	State *ControlState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ControlAck) Reset() {
	*x = ControlAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlAck) ProtoMessage() {}

func (x *ControlAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlAck.ProtoReflect.Descriptor instead.
func (*ControlAck) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{3}
}

func (x *ControlAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ControlAck) GetState() *ControlState {
	if x != nil {
		return x.State
	}
	return nil
}

type ControlError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Human-friendly description of why an update failed.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ControlError) Reset() {
	*x = ControlError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlError) ProtoMessage() {}

func (x *ControlError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlError.ProtoReflect.Descriptor instead.
func (*ControlError) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{4}
}

func (x *ControlError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ControlMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Control:
	//
	//	*ControlMessage_Update
	//	*ControlMessage_State
	//	*ControlMessage_Ack
	//	*ControlMessage_Error
	Control isControlMessage_Control `protobuf_oneof:"control"`
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{5}
}

func (m *ControlMessage) GetControl() isControlMessage_Control {
	if m != nil {
		return m.Control
	}
	return nil
}

func (x *ControlMessage) GetUpdate() *ControlUpdate {
	if x, ok := x.GetControl().(*ControlMessage_Update); ok {
		return x.Update
	}
	return nil
}

func (x *ControlMessage) GetState() *ControlState {
	if x, ok := x.GetControl().(*ControlMessage_State); ok {
		return x.State
	}
	return nil
}

func (x *ControlMessage) GetAck() *ControlAck {
	if x, ok := x.GetControl().(*ControlMessage_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *ControlMessage) GetError() *ControlError {
	if x, ok := x.GetControl().(*ControlMessage_Error); ok {
		return x.Error
	}
	return nil
}

type isControlMessage_Control interface {
	isControlMessage_Control()
}

type ControlMessage_Update struct {
	Update *ControlUpdate `protobuf:"bytes,1,opt,name=update,proto3,oneof"`
}

type ControlMessage_State struct {
	State *ControlState `protobuf:"bytes,2,opt,name=state,proto3,oneof"`
}

type ControlMessage_Ack struct {
	Ack *ControlAck `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type ControlMessage_Error struct {
	Error *ControlError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ControlMessage_Update) isControlMessage_Control() {}

func (*ControlMessage_State) isControlMessage_Control() {}

func (*ControlMessage_Ack) isControlMessage_Control() {}

func (*ControlMessage_Error) isControlMessage_Control() {}

var File_proto_control_proto protoreflect.FileDescriptor

var file_proto_control_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x61, 0x6e, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x61,
	0x22, 0x75, 0x0a, 0x12, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69,
	0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69,
	0x74, 0x79, 0x12, 0x43, 0x0a, 0x1e, 0x64, 0x65, 0x61, 0x74, 0x68, 0x5f, 0x72, 0x61, 0x74, 0x65,
	0x5f, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x1b, 0x64, 0x65, 0x61, 0x74,
	0x68, 0x52, 0x61, 0x74, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x22, 0xa2, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x6c, 0x6f, 0x63, 0x6b, 0x64, 0x6f,
	0x77, 0x6e, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0f, 0x6c, 0x6f, 0x63, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x12, 0x39, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x61, 0x6e, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x61, 0x2e,
	0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x22, 0x84, 0x02, 0x0a,
	0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x34, 0x0a,
	0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x70, 0x61, 0x6e, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x6e, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x3e,
	0x0a, 0x1b, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x64, 0x65, 0x61, 0x74,
	0x68, 0x5f, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x19, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x44, 0x65,
	0x61, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1e,
	0x0a, 0x0a, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x12, 0x33,
	0x0a, 0x15, 0x69, 0x6e, 0x66, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x62,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x14, 0x69,
	0x6e, 0x66, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x22, 0x55, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x41, 0x63,
	0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x61, 0x6e,
	0x64, 0x65, 0x6d, 0x69, 0x63, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x28, 0x0a, 0x0c, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0xdc, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x61, 0x6e, 0x64, 0x65, 0x6d,
	0x69, 0x63, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x61, 0x6e,
	0x64, 0x65, 0x6d, 0x69, 0x63, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x29, 0x0a, 0x03,
	0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x61, 0x6e, 0x64,
	0x65, 0x6d, 0x69, 0x63, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x41, 0x63, 0x6b,
	0x48, 0x00, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x2f, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x61, 0x6e, 0x64, 0x65, 0x6d, 0x69,
	0x63, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48,
	0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x61, 0x6e, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x61,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_control_proto_rawDescOnce sync.Once
	file_proto_control_proto_rawDescData = file_proto_control_proto_rawDesc
)

func file_proto_control_proto_rawDescGZIP() []byte {
	file_proto_control_proto_rawDescOnce.Do(func() {
		file_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_control_proto_rawDescData)
	})
	return file_proto_control_proto_rawDescData
}

var file_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_control_proto_goTypes = []any{
	(*HospitalParameters)(nil), // 0: pandemica.HospitalParameters
	(*ControlUpdate)(nil),      // 1: pandemica.ControlUpdate
	(*ControlState)(nil),       // 2: pandemica.ControlState
	(*ControlAck)(nil),         // 3: pandemica.ControlAck
	(*ControlError)(nil),       // 4: pandemica.ControlError
	(*ControlMessage)(nil),     // 5: pandemica.ControlMessage
}
var file_proto_control_proto_depIdxs = []int32{
	0, // 0: pandemica.ControlUpdate.hospital:type_name -> pandemica.HospitalParameters
	1, // 1: pandemica.ControlState.settings:type_name -> pandemica.ControlUpdate
	2, // 2: pandemica.ControlAck.state:type_name -> pandemica.ControlState
	1, // 3: pandemica.ControlMessage.update:type_name -> pandemica.ControlUpdate
	2, // 4: pandemica.ControlMessage.state:type_name -> pandemica.ControlState
	3, // 5: pandemica.ControlMessage.ack:type_name -> pandemica.ControlAck
	4, // 6: pandemica.ControlMessage.error:type_name -> pandemica.ControlError
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_control_proto_init() }
func file_proto_control_proto_init() {
	if File_proto_control_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_control_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HospitalParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ControlUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ControlState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ControlAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ControlError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ControlMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_control_proto_msgTypes[5].OneofWrappers = []any{
		(*ControlMessage_Update)(nil),
		(*ControlMessage_State)(nil),
		(*ControlMessage_Ack)(nil),
		(*ControlMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_control_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_control_proto_goTypes,
		DependencyIndexes: file_proto_control_proto_depIdxs,
		MessageInfos:      file_proto_control_proto_msgTypes,
	}.Build()
	File_proto_control_proto = out.File
	file_proto_control_proto_rawDesc = nil
	file_proto_control_proto_goTypes = nil
	file_proto_control_proto_depIdxs = nil
}
